export const config = {
  zIndexBase: 40,
  layoutStabilizationMs: 450,
  cascadeOffset: 30,
  cooldownMs: 500,
  maxWindows: 10,
  snapGap: 6,
  taskbarHeight: 64,
  snapThreshold: 30,
  dragThreshold: 10,
  resizeDebounceMs: 6,
  animationDurationMs: 400,
  defaultWidth: 800,
  defaultHeight: 600,
  minMargin: 10,
  edgeDetectionRatio: 0.4,
  scrollRestoreTimeoutMs: 2000,
};
